spring:
  data:
    mongodb:
      uri: mongodb://localhost:27817/product-service
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0